services:
  - type: web
    name: web-vuln-scanner-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
